/*----- PROTECTED REGION ID(LiberaSinglePassEStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LiberaSinglePassEStateMachine.cpp
//
// description : C++ source for the �name� and its alowed
//               methods for commands and attributes
//
// project :     Libera Brillance Single Pass E.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <LiberaSinglePassE.h>
#include <LiberaSinglePassEClass.h>

/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::LiberaSinglePassEStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  The Libera box is up and running
//  UNKNOWN  |  No possible communication with the Libera box
//  FAULT    |  The Libera box is in Fault


namespace LiberaSinglePassE_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ADCBufferSize_allowed()
 *	Description : Execution allowed for ADCBufferSize attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_ADCBufferSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ADCBufferSize attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ADCBufferSizeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ADCBufferSizeStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(LiberaSinglePassE::ADCBufferSizeStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ADCBufferSizeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_TriggerCounter_allowed()
 *	Description : Execution allowed for TriggerCounter attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_TriggerCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(LiberaSinglePassE::TriggerCounterStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::TriggerCounterStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Fan1Speed_allowed()
 *	Description : Execution allowed for Fan1Speed attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Fan1Speed_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Fan1Speed attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Fan1SpeedStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Fan1SpeedStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Fan2Speed_allowed()
 *	Description : Execution allowed for Fan2Speed attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Fan2Speed_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(LiberaSinglePassE::Fan2SpeedStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Fan2SpeedStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Temp1_allowed()
 *	Description : Execution allowed for Temp1 attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Temp1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(LiberaSinglePassE::Temp1StateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Temp1StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Temp2_allowed()
 *	Description : Execution allowed for Temp2 attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Temp2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(LiberaSinglePassE::Temp2StateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Temp2StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Temp3_allowed()
 *	Description : Execution allowed for Temp3 attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Temp3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(LiberaSinglePassE::Temp3StateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Temp3StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Calibration_ka_allowed()
 *	Description : Execution allowed for Calibration_ka attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Calibration_ka_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Calibration_ka attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kaStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kaStateAllowed_WRITE

	//	Not any excluded states for Calibration_ka attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kaStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kaStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Calibration_kb_allowed()
 *	Description : Execution allowed for Calibration_kb attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Calibration_kb_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Calibration_kb attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kbStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kbStateAllowed_WRITE

	//	Not any excluded states for Calibration_kb attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kbStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kbStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Calibration_kc_allowed()
 *	Description : Execution allowed for Calibration_kc attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Calibration_kc_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Calibration_kc attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kcStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kcStateAllowed_WRITE

	//	Not any excluded states for Calibration_kc attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kcStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kcStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Calibration_kd_allowed()
 *	Description : Execution allowed for Calibration_kd attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Calibration_kd_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Calibration_kd attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kdStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kdStateAllowed_WRITE

	//	Not any excluded states for Calibration_kd attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Calibration_kdStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Calibration_kdStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_x_k_allowed()
 *	Description : Execution allowed for Linear_x_k attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_x_k_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_x_k attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_x_kStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_x_kStateAllowed_WRITE

	//	Not any excluded states for Linear_x_k attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_x_kStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_x_kStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_x_offs_allowed()
 *	Description : Execution allowed for Linear_x_offs attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_x_offs_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_x_offs attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_x_offsStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_x_offsStateAllowed_WRITE

	//	Not any excluded states for Linear_x_offs attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_x_offsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_x_offsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_y_k_allowed()
 *	Description : Execution allowed for Linear_y_k attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_y_k_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_y_k attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_y_kStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_y_kStateAllowed_WRITE

	//	Not any excluded states for Linear_y_k attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_y_kStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_y_kStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_y_offs_allowed()
 *	Description : Execution allowed for Linear_y_offs attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_y_offs_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_y_offs attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_y_offsStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_y_offsStateAllowed_WRITE

	//	Not any excluded states for Linear_y_offs attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_y_offsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_y_offsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_q_k_allowed()
 *	Description : Execution allowed for Linear_q_k attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_q_k_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_q_k attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_q_kStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_q_kStateAllowed_WRITE

	//	Not any excluded states for Linear_q_k attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_q_kStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_q_kStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_q_offs_allowed()
 *	Description : Execution allowed for Linear_q_offs attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_q_offs_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_q_offs attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_q_offsStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_q_offsStateAllowed_WRITE

	//	Not any excluded states for Linear_q_offs attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_q_offsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_q_offsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_sum_k_allowed()
 *	Description : Execution allowed for Linear_sum_k attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_sum_k_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_sum_k attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_sum_kStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_sum_kStateAllowed_WRITE

	//	Not any excluded states for Linear_sum_k attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_sum_kStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_sum_kStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Linear_sum_offs_allowed()
 *	Description : Execution allowed for Linear_sum_offs attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Linear_sum_offs_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Linear_sum_offs attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_sum_offsStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_sum_offsStateAllowed_WRITE

	//	Not any excluded states for Linear_sum_offs attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Linear_sum_offsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Linear_sum_offsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Signal_expansion_allowed()
 *	Description : Execution allowed for Signal_expansion attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Signal_expansion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Signal_expansion attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Signal_expansionStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Signal_expansionStateAllowed_WRITE

	//	Not any excluded states for Signal_expansion attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Signal_expansionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Signal_expansionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Interlock_enabled_allowed()
 *	Description : Execution allowed for Interlock_enabled attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Interlock_enabled_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Interlock_enabled attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Interlock_enabledStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Interlock_enabledStateAllowed_WRITE

	//	Not any excluded states for Interlock_enabled attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Interlock_enabledStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Interlock_enabledStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Limit_min_x_allowed()
 *	Description : Execution allowed for Limit_min_x attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Limit_min_x_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Limit_min_x attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_min_xStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_min_xStateAllowed_WRITE

	//	Not any excluded states for Limit_min_x attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_min_xStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_min_xStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Limit_min_y_allowed()
 *	Description : Execution allowed for Limit_min_y attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Limit_min_y_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Limit_min_y attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_min_yStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_min_yStateAllowed_WRITE

	//	Not any excluded states for Limit_min_y attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_min_yStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_min_yStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Limit_max_x_allowed()
 *	Description : Execution allowed for Limit_max_x attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Limit_max_x_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Limit_max_x attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_max_xStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_max_xStateAllowed_WRITE

	//	Not any excluded states for Limit_max_x attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_max_xStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_max_xStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Limit_max_y_allowed()
 *	Description : Execution allowed for Limit_max_y attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Limit_max_y_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Limit_max_y attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_max_yStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_max_yStateAllowed_WRITE

	//	Not any excluded states for Limit_max_y attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Limit_max_yStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Limit_max_yStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Overflow_threshold_allowed()
 *	Description : Execution allowed for Overflow_threshold attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Overflow_threshold_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Overflow_threshold attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Overflow_thresholdStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Overflow_thresholdStateAllowed_WRITE

	//	Not any excluded states for Overflow_threshold attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Overflow_thresholdStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Overflow_thresholdStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Interlock_status_allowed()
 *	Description : Execution allowed for Interlock_status attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Interlock_status_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Interlock_status attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Interlock_statusStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Interlock_statusStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Status_x_allowed()
 *	Description : Execution allowed for Status_x attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Status_x_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Status_x attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Status_xStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Status_xStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Status_y_allowed()
 *	Description : Execution allowed for Status_y attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Status_y_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Status_y attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Status_yStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Status_yStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Status_adc_overflow_allowed()
 *	Description : Execution allowed for Status_adc_overflow attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Status_adc_overflow_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Status_adc_overflow attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::Status_adc_overflowStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::Status_adc_overflowStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_X_allowed()
 *	Description : Execution allowed for X attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_X_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for X attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::XStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::XStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Y_allowed()
 *	Description : Execution allowed for Y attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Y_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Y attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::YStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::YStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Sum_allowed()
 *	Description : Execution allowed for Sum attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Sum_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Sum attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::SumStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::SumStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_EnableADC_allowed()
 *	Description : Execution allowed for EnableADC attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_EnableADC_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for EnableADC attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::EnableADCStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::EnableADCStateAllowed_WRITE

	//	Not any excluded states for EnableADC attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::EnableADCStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::EnableADCStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Q_allowed()
 *	Description : Execution allowed for Q attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Q_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Q attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::QStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::QStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ADCChannelA_allowed()
 *	Description : Execution allowed for ADCChannelA attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_ADCChannelA_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ADCChannelA attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ADCChannelAStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ADCChannelAStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ADCChannelB_allowed()
 *	Description : Execution allowed for ADCChannelB attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_ADCChannelB_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ADCChannelB attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ADCChannelBStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ADCChannelBStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ADCChannelC_allowed()
 *	Description : Execution allowed for ADCChannelC attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_ADCChannelC_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ADCChannelC attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ADCChannelCStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ADCChannelCStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ADCChannelD_allowed()
 *	Description : Execution allowed for ADCChannelD attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_ADCChannelD_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ADCChannelD attribute in read access.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ADCChannelDStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ADCChannelDStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::ON ||
		get_state()==Tango::UNKNOWN)
	{
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ResetStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ResetStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ResetInterlockStatus_allowed()
 *	Description : Execution allowed for ResetInterlockStatus attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_ResetInterlockStatus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ResetInterlockStatus command.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::ResetInterlockStatusStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ResetInterlockStatusStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_MagicCommand_allowed()
 *	Description : Execution allowed for MagicCommand attribute
 */
//--------------------------------------------------------
bool LiberaSinglePassE::is_MagicCommand_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MagicCommand command.
	/*----- PROTECTED REGION ID(LiberaSinglePassE::MagicCommandStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::MagicCommandStateAllowed
	return true;
}

}	//	End of namespace
