/*----- PROTECTED REGION ID(LiberaSinglePassEStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LiberaSinglePassEStateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     Libera Brillance Single Pass E.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <LiberaSinglePassE.h>
#include <LiberaSinglePassEClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * LiberaSinglePassE states description:
 *
 * ON :	The Libera box is up and running 
 * UNKNOWN :	No possible communication with the Libera box 
 * FAULT :	The Libera box is in Fault 
 */

namespace LiberaSinglePassE_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_BufferSizeState_allowed()
 *	Description : Execution allowed for BufferSize attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_BufferSize_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for BufferSize attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaSinglePassE::BufferSizeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::BufferSizeStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_BufferSizeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_BufferSizeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_LevelState_allowed()
 *	Description : Execution allowed for Level attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Level_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Level attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaSinglePassE::LevelStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::LevelStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_LevelStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_LevelStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_TriggerCounterState_allowed()
 *	Description : Execution allowed for TriggerCounter attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_TriggerCounter_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_TriggerCounterStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_TriggerCounterStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Fan1SpeedState_allowed()
 *	Description : Execution allowed for Fan1Speed attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Fan1Speed_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_Fan1SpeedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_Fan1SpeedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Fan2SpeedState_allowed()
 *	Description : Execution allowed for Fan2Speed attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Fan2Speed_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_Fan2SpeedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_Fan2SpeedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Temp1State_allowed()
 *	Description : Execution allowed for Temp1 attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Temp1_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_Temp1StateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_Temp1StateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Temp2State_allowed()
 *	Description : Execution allowed for Temp2 attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Temp2_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_Temp2StateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_Temp2StateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_Temp3State_allowed()
 *	Description : Execution allowed for Temp3 attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Temp3_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_Temp3StateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_Temp3StateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_UpState_allowed()
 *	Description : Execution allowed for Up attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Up_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_UpStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_UpStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_DownState_allowed()
 *	Description : Execution allowed for Down attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Down_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_DownStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_DownStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_LeftState_allowed()
 *	Description : Execution allowed for Left attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Left_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_LeftStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_LeftStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_RightState_allowed()
 *	Description : Execution allowed for Right attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Right_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_RightStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_RightStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_UpTState_allowed()
 *	Description : Execution allowed for UpT attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_UpT_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_UpTStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_UpTStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_DownTState_allowed()
 *	Description : Execution allowed for DownT attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_DownT_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_DownTStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_DownTStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_LeftTState_allowed()
 *	Description : Execution allowed for LeftT attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_LeftT_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_LeftTStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_LeftTStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_RightTState_allowed()
 *	Description : Execution allowed for RightT attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_RightT_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_RightTStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_RightTStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ZpositionState_allowed()
 *	Description : Execution allowed for Zposition attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Zposition_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_ZpositionStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_ZpositionStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_XpositionState_allowed()
 *	Description : Execution allowed for Xposition attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Xposition_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_XpositionStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_XpositionStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_CurrentState_allowed()
 *	Description : Execution allowed for Current attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Current_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_CurrentStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_CurrentStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_SumTState_allowed()
 *	Description : Execution allowed for SumT attribute.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_SumT_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(LiberaSinglePassE::read_SumTStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::read_SumTStateAllowed_READ

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(LiberaSinglePassE::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================


//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ResetState_allowed()
 *	Description : Execution allowed for Reset command.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_Reset_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::ON	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(LiberaSinglePassE::ResetStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ResetStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaSinglePassE::is_ResetTriggerState_allowed()
 *	Description : Execution allowed for ResetTrigger command.
 */
//--------------------------------------------------------

bool LiberaSinglePassE::is_ResetTrigger_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaSinglePassE::ResetTriggerStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::ResetTriggerStateAllowed

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(LiberaSinglePassE::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	LiberaSinglePassE::are_dynamic_commands_allowed

}	// namespace LiberaSinglePassE_ns
